services:
  - type: web
    name: obesity-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    environment:
      - key: PYTHON_VERSION
        value: 3.10
